using System;

public enum RESOURCE_ID
{
	START_TO_VERIFICATION,
	WRITE_BLOCK,
	READ_BLOCK,
	VERIFY_BLOCK,
	VERIFY_BLOCK_DONE,
	INVALID_BUFFER,
	ERR_UNAVAILABLE_PORT,
	MSG_USB_HAS_BEEN_CONNECTED,
	MSG_USB_HAS_BEEN_REMOVED,
	ERR_INVALID_REPORT_ID,
	ERR_INVALID_USER_DEFINE_COMMAND,
	MSG_PORT_OPEN,
	MSG_INTIALIZE_CONNECT_PORT
}
