using System;

public enum SMBUS_ERRCODE
{
	SMBUS_ERROR_NORMAL,
	SMBUS_ERROR_ADDRESS,
	SMBUS_ERROR_NO_ACK,
	SMBUS_ERROR_ARBITRATION = 4,
	SMBUS_ERROR_COMMAND = 8,
	SMBUS_ERROR_TIMEOUT = 16,
	SMBUS_ERROR_BUSY = 32,
	SMBUS_ERROR_UNKNOWN = 255
}
