language: c
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib cmake
before_script:
  - cmake source/compiler -DCMAKE_C_FLAGS=-m32 -DCPACK_GENERATOR=TGZ
script:
  - make
  - make package
