version: '{build}'

configuration:
  - RelWithDebInfo

before_build:
  - cmake -G "Visual Studio 10 2010" source/compiler -DCPACK_GENERATOR=ZIP

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

artifacts:
  - path: pawnc-*-windows.zip
    name: Binary package
